version: '3.8'

services:
  wyoming-whisper-trt:
    build: .
    ports:
      - "10300:10300"
    volumes:
      - ./data:/data
      - ~/.cache/whisper_trt:/root/.cache/whisper_trt
      # Mount host whisper_trt installation if available
      - /usr/local/lib/python3.8/dist-packages:/opt/host-packages:ro
    environment:
      - PYTHONPATH=/opt/host-packages:${PYTHONPATH}
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    command: [
      "--uri", "tcp://0.0.0.0:10300",
      "--model", "tiny.en",
      "--data-dir", "/data",
      "--debug"
    ]
    restart: unless-stopped